### ISSUE TITLE
v2 budget assertions seem wrong

### ISSUE THREAD

**Issue by milesalex** [treosh/lighthouse-ci-action#13]
One more thing...

I just tested with the NPM module and I have set my budgets correctly:

![image](https://user-images.githubusercontent.com/421362/68727323-10984480-0592-11ea-95d7-83f7dbc4ab12.png)

The 1KB over budged is expected. Using this action All my budgets are  failing and I dont know what scale the numbers are in

![image](https://user-images.githubusercontent.com/421362/68727367-39b8d500-0592-11ea-9288-6a107084c097.png)

**Comment by denar90** [comment]
Hey @milesalex.
First of all, sorry for the delay and thank you for pointing out the issue.

So, actually there are 2 problems:
1. Assertion for `resource-summary` compared Kilobytes (values set via budget config) and Bytes (values measured from the site). It's [fixed now in LHCI](https://github.com/GoogleChrome/lighthouse-ci/pull/97) and after release will be fixed in Action.
2. What you will still see - numbers without actual unit symbol. It has to be handled by https://github.com/GoogleChrome/lighthouse-ci/issues/100. But for now, values you see in console are bytes.

**Comment by alekseykulikov** [comment]
Fixed by the recent release, see the recipe for more details: https://github.com/treosh/lighthouse-ci-action/actions?query=workflow%3ALHCI-assert-on-budget
