### ISSUE TITLE
feature request: report results as a PR comment?

### ISSUE THREAD

**Issue by ooloth** [treosh/lighthouse-ci-action#17]
Thanks for this project!

Would it be possible to see the results of each Lighthouse audit as a comment on the PR (similar to the behaviour of the deprecated [lighthousebot](https://github.com/GoogleChromeLabs/lighthousebot) project)?

**Comment by robinmetral** [comment]
FYI, the Typescript website repo has something like this set up using a Danger plugin, [danger-plugin-lighthouse](https://github.com/orta/danger-plugin-lighthouse) (by @orta).

It looks like this:

| source: https://github.com/microsoft/TypeScript-Website/pull/121 |
| --- |
| ![Screenshot_2019-11-25 Fill out the TS Config reference by orta · Pull Request #121 · microsoft TypeScript-Website](https://user-images.githubusercontent.com/35560568/69524481-6bed0e00-0f66-11ea-90cf-4931b737324b.png) |

I agree that it would be nice to make this possible in this action without a Danger dep :slightly_smiling_face:

**Comment by orta** [comment]
Yeah, I think might be able to provide some text inside inside a GitHub check (Danger has this [as a feature](https://github.com/danger/danger-js/runs/25158543)). 

I found it a particularly weak use-case for anything which isn't an obvious hard pass/fail though because no one will click through to see the results if it's not blocking their way. Via an GH action you don't have enough auth to write a comment though, so it probably is the best option.

That said - if you do, I'd love to share ideas on the results JSON -> markdown rendering

**Comment by exterkamp** [comment]
> That said - if you do, I'd love to share ideas on the results JSON -> markdown rendering

We have been playing with the idea of using the markdown results of the check as output here #2. But since this is an action it is a bit limited vs. a full app on what we can do in the action native status, we basically have to post a new status.

> Via an GH action you don't have enough auth to write a comment though

We can get a client to do git stuff, like post statuses and _I think_  comments [with the octokit client](https://github.com/actions/toolkit/tree/master/packages/github) via  [pulls.createComment](https://octokit.github.io/rest.js/#octokit-routes-pulls-create-comment)

**Comment by paulirish** [comment]
Please also see https://github.com/treosh/lighthouse-ci-action/issues/2#issuecomment-558395025 where I summarized some of the options we have.

**Comment by alekseykulikov** [comment]
From our experience, a comment for each PR provides more noise, than value. To track the history, it's better to use LHCI Server. If the tests fail, the action uses annotations https://github.com/treosh/lighthouse-ci-action/issues/2#issuecomment-601456805
